from typing import Dict, Any, List


class DesignReviewAgent:
    """
    Design Review Agent for AI-assisted Mechanical Reliability.

    Role:
    - Review and interpret reliability pipeline outputs
    - Highlight risk implications and assumption sensitivity
    - Raise engineering review questions

    Non-goals (Explicitly Out of Scope):
    - Making design decisions
    - Recommending geometry or material changes
    - Issuing pass/fail judgments
    """

    def review(
        self,
        pipeline_output: Dict[str, Any]
    ) -> Dict[str, Any]:
        """
        Review reliability pipeline output and generate structured review notes.

        Parameters
        ----------
        pipeline_output : dict
            Output generated by run_reliability_pipeline()

        Returns
        -------
        dict
            Structured design review notes without design authority
        """

        context = pipeline_output.get("context", {})
        risk_score = pipeline_output.get("risk_score")
        risk_level = pipeline_output.get("risk_level")
        top_risks = pipeline_output.get("top_risk_factors", [])
        assumptions = pipeline_output.get("assumptions", [])
        limitations = pipeline_output.get("limitations", [])

        return {
            "review_context": {
                "test_type": context.get("test_type"),
                "system_scope": context.get("system_scope"),
                "impact_scenario": context.get("impact_scenario"),
            },
            "risk_interpretation": self._interpret_risk_level(
                risk_score, risk_level
            ),
            "key_risk_observations": self._summarize_top_risks(top_risks),
            "assumption_sensitivity": self._review_assumptions(assumptions),
            "review_questions": self._generate_review_questions(
                top_risks, assumptions
            ),
            "review_limitations": limitations,
            "agent_disclaimer": self._disclaimer(),
        }

    # ---------- Internal helper methods (no external authority) ----------

    def _interpret_risk_level(
        self, risk_score: float, risk_level: str
    ) -> str:
        return (
            f"The inferred risk level is '{risk_level}' "
            f"(score={risk_score:.2f}). "
            "This represents a relative risk indication under the stated assumptions, "
            "not a design acceptance decision."
        )

    def _summarize_top_risks(
        self, top_risks: List[Dict[str, Any]]
    ) -> List[str]:
        summaries = []
        for risk in top_risks:
            summaries.append(
                f"Proxy '{risk.get('proxy')}' shows trend '{risk.get('trend')}', "
                f"with relative contribution {risk.get('contribution')}."
            )
        return summaries

    def _review_assumptions(
        self, assumptions: List[str]
    ) -> List[str]:
        return [
            f"This result is sensitive to the assumption: '{assumption}'. "
            "Deviation from this assumption may alter the inferred risk ranking."
            for assumption in assumptions
        ]

    def _generate_review_questions(
        self,
        top_risks: List[Dict[str, Any]],
        assumptions: List[str],
    ) -> List[str]:
        questions = []

        for risk in top_risks:
            questions.append(
                f"Has the proxy '{risk.get('proxy')}' been validated "
                "against physical test data or prior design experience?"
            )

        for assumption in assumptions:
            questions.append(
                f"Is assumption '{assumption}' acceptable for the current design phase?"
            )

        return questions

    def _disclaimer(self) -> str:
        return (
            "This review output is intended to support engineering discussion only. "
            "It does not constitute a design recommendation, approval, or rejection."
        )
